<?php
        $def_dados = array('global'          => array('objeto'                    => '',
                                                      'metodo'                    => 'N',
                                                      'tipo'                      => '',
                                                      'multipla'                  => 'N',
                                                      'altura'                    => 1,
                                                      'altura_ajax'               => 10,
                                                      'delimitador'               => '',
                                                      'desl_global'               => '',
                                                      'titulo'                    => '',
                                                      'titulo_flag'               => 'N',
                                                      'def_ajax_edit_cap_texto'   => 'N',
                                                      'def_ajax_edit_like'        => 'qqparte',
                                                      'def_ajax_edit_label'       => '',
                                                      'def_ajax_edit_largura'     => 30,
                                                      'def_ajax_edit_case'        => 'N',
                                                      'iteracoes'                 => 1,
                                                      'separador'                 => '',
                                                      'entra'                     => 3),
                          'conteudo'         => array(),
                          'relacoes'         => array(),
                          'select'           => '',
                          'original'         => '',
                          'permitir_valor_branco'         => '',
                          'lookup_delimitador'         => '',
                          'connection'       => '',
                          'chk_opt_mark_all' => 'N');
?>