<?php
$def_dados = array('prefs' => array(
        'schema'       		               => 'scriptcase9',
        'list_cols'    		               => 'UGS',
        'show_friendly_name'               => 'Y',
        'page_time'    		               => 'N',
        'page_query'   		               => 'N',
        'win_option'   		               => '',
        'popup_hint'   		               => 'Y',
        'sec_flag'     		               => 'Y',
        'sec_pass'                         => 'Y',
        'popup_init'   		               => 'Y',
        'popup_wizard' 		               => 'Y',
        'popup_editor' 		               => 'Y',
        'language'			               => '',
        'app_list_menu_width'              => '260px',
        'app_list_inc'                     => '5',
        'app_edit_menu_width'              => '260px',
        'app_edit_inc'                     => '5',
        'popup_dt_suporte'                 => 'Y',
        'popup_dt_upgrade'                 => 'Y',
        'msg_change_publish'               => 'N',
        'password_md5'                     => '',
        'password_md5_usar'                => 'N',
        'password_md5_qtd'                 => '0',
        'sc_start'                         => 'intro',
        'tour_empty_projects'              => 'N',
        'tour_new_project_empty_projects'  => 'N',
        'auto_save'			               => 'N',
        'sc_event_editor'                  => 'Y',
        'sc_event_editor_precodes'         => 'Y',
        'sc_editor_indentWithTabs'         => 'Y',
        'sc_event_editor_theme'            => 'default',
        'tip_apps'                         => 'Y',
        'check_folders'                    => 'folders',
        'use_hotkeys'                      => 'Y',
        'editor_features'                  => 'Y',
        'run_app_enabled'                  => 'N',
        'run_app_warning_display'          => 'Y',
        'create_grid_form_enabled'         => 'N',
        'create_grid_form_warning_display' => 'Y',
        'wizard_form_warning_display'      => 'Y',
    )
);
?>